import type { Metadata } from "next";
import { Inter } from "next/font/google";
import "./globals.css";
import { Space_Mono, Roboto } from 'next/font/google'

const inter = Inter({ subsets: ["latin"] });

export const metadata: Metadata = {
  title: "Create Next App",
  description: "Generated by create next app",
};

const bodyFont = Space_Mono({
  subsets: ['latin'],
  weight: ['400', '700'], // add the weights you need
})

const headingFont = Roboto({
  subsets: ['latin'],
  weight: ['400', '700'], // add the weights you need
})


// export default function RootLayout({
//   children,
// }: Readonly<{
//   children: React.ReactNode;
// }>) {
//   return (
//     <html lang="en">
//       <body className={inter.className}>{children}</body>
//     </html>
export default function RootLayout({ children }: Readonly<{ children: React.ReactNode }>) {
  return (
    <html lang="en" className={`${bodyFont.className} ${headingFont.className}`}>
      <body className={bodyFont.className}>{children}</body>
    </html>
  )
}