/**
* This code was generated by v0 by Vercel.
* @see https://v0.dev/t/O6RxisUUAdQ
* Documentation: https://v0.dev/docs#integrating-generated-code-into-your-nextjs-app
*/

/** Add fonts into your Next.js project:

import { Crimson_Text } from 'next/font/google'
import { Yeseva_One } from 'next/font/google'

crimson_text({
  subsets: ['latin'],
  display: 'swap',
})

yeseva_one({
  subsets: ['latin'],
  display: 'swap',
})

To read more about using these font, please visit the Next.js documentation:
- App Directory: https://nextjs.org/docs/app/building-your-application/optimizing/fonts
- Pages Directory: https://nextjs.org/docs/pages/building-your-application/optimizing/fonts
**/
import Link from "next/link"
import { Card } from "@/components/ui/card"
import { Input } from "@/components/ui/input"
import { Textarea } from "@/components/ui/textarea"
import { Button } from "@/components/ui/button"
import Image from 'next/image'

export function landing() {
  return (
    <div className="flex flex-col min-h-[100dvh]">
      <header className="px-4 lg:px-6 h-14 flex items-center">
        <Link href="#" className="flex items-center justify-center" prefetch={false}>
          <TruckIcon className="h-6 w-6" />
          <span className="text-2xl font-bold pl-2"> Pinoy Eats</span>
        </Link>
        <nav className="ml-auto flex gap-4 sm:gap-6">
          <Link href="#" className="text-sm font-medium hover:underline underline-offset-4" prefetch={false}>
            Menu
          </Link>
          <Link href="#testimonials" className="text-sm font-medium hover:underline underline-offset-4" prefetch={false}>
            Testimonials
          </Link>
          <Link href="#contact" className="text-sm font-medium hover:underline underline-offset-4" prefetch={false}>
            Contact
          </Link>
        </nav>
      </header>
      <main className="flex-1 ">
        <section className="w-full py-12 sm:py-24 md:py-32 lg:py-40 bg-[url('/hero-bg.jpg')] bg-cover bg-center flex items-center justify-center">
          <div className="container px-4 md:px-6 text-center text-primary-foreground">
          <div className="flex items-center justify-center">
      <Image src="https://doodleipsum.com/700?i=913361545e1655bb33bf99af1f980869" alt="hero-bg" width={500} height={500} />          
    </div>
            <h1 className="text-4xl font-bold tracking-tighter sm:text-5xl md:text-6xl">Authentic Filipino Flavors</h1>
            <p className="max-w-[600px] mx-auto mt-4 text-lg md:text-xl">
              Discover the vibrant tastes of the Philippines with our family-owned food truck.
            </p>
            <div className="mt-8">
              <Link
                href="#"
                className="inline-flex h-10 items-center justify-center rounded-md bg-primary px-8 text-sm font-medium text-primary-foreground shadow transition-colors hover:bg-primary/90 focus-visible:outline-none focus-visible:ring-1 focus-visible:ring-ring disabled:pointer-events-none disabled:opacity-50"
                prefetch={false}
              >
                Order Now
              </Link>
              
            </div>
            
          </div>
        </section>
        <section id="menu" className="w-full py-12 sm:py-24 md:py-32 flex items-center justify-center">
          <div className="container px-4 md:px-6 max-w-5xl mx-auto">
            <div className="text-center space-y-4">
              <h2 className="text-3xl font-bold tracking-tighter sm:text-4xl md:text-5xl">Our Delicious Menu</h2>
              <p className="max-w-[600px] mx-auto text-muted-foreground md:text-xl/relaxed">
                Explore our mouthwatering selection of authentic Filipino dishes.
              </p>
            </div>
            <div className="grid gap-8 mt-8 sm:grid-cols-2 lg:grid-cols-3">
              <div className="flex flex-col items-center">
                <Image
                  src="/lumpia.jpg"
                  width="300"
                  height="200"
                  alt="Lumpia"
                  className="rounded-xl w-full h-[200px] object-cover"
                  style={{ aspectRatio: "300/200", objectFit: "cover" }}
                />
                <div className="mt-4 text-center">
                  <h3 className="text-xl font-bold">Lumpia</h3>
                  <p className="text-muted-foreground mt-1">
                    Crispy spring rolls filled with savory pork and vegetables.
                  </p>
                </div>
              </div>
              <div className="flex flex-col items-center">
                <Image
                  src="/adobo.jpg"
                  width="300"
                  height="200"
                  alt="Adobo"
                  className="rounded-xl w-full h-[200px] object-cover"
                  style={{ aspectRatio: "300/200", objectFit: "cover" }}
                />
                <div className="mt-4 text-center">
                  <h3 className="text-xl font-bold">Adobo</h3>
                  <p className="text-muted-foreground mt-1">
                    Tender chicken or pork simmered in a savory soy and vinegar sauce.
                  </p>
                </div>
              </div>
              <div className="flex flex-col items-center">
                <Image
                  src="/halo-halo.jpg"
                  width="300"
                  height="200"
                  alt="Halo-Halo"
                  className="rounded-xl w-full h-[200px] object-cover"
                  style={{ aspectRatio: "300/200", objectFit: "cover" }}
                />
                <div className="mt-4 text-center">
                  <h3 className="text-xl font-bold">Halo-Halo</h3>
                  <p className="text-muted-foreground mt-1">
                    A refreshing dessert with shaved ice, evaporated milk, and various sweet ingredients.
                  </p>
                </div>
              </div>
            </div>
          </div>
        </section>
        <section id="testimonials" className="w-full py-12 sm:py-24 md:py-32 bg-muted flex items-center justify-center">
          <div className="container px-4 md:px-6 max-w-5xl mx-auto">
            <div className="text-center space-y-4">
              <h2 className="text-3xl font-bold tracking-tighter sm:text-4xl md:text-5xl">What Our Customers Say</h2>
              <p className="max-w-[600px] mx-auto text-muted-foreground md:text-xl/relaxed">
                Hear from our satisfied customers about their experience with Pinoy Eats.
              </p>
            </div>
            <div className="grid gap-8 mt-8 sm:grid-cols-2 lg:grid-cols-3">
            <Card className="bg-background p-6 rounded-xl shadow-sm">
                <div className="flex items-center gap-4">
                  <div className="rounded-full bg-primary text-primary-foreground w-12 h-12 flex items-center justify-center">
                    JD
                  </div>
                  <div>
                    <h4 className="font-bold">Justin Blanco</h4>
                    <p className="text-sm text-muted-foreground">Extremely Satisfied Customer</p>
                  </div>
                </div>
                <p className="mt-4 text-muted-foreground">
                  &ldquo;This food truck changed my life completely! I will never be the same again.&rdquo;
                </p>
              </Card>
              <Card className="bg-background p-6 rounded-xl shadow-sm">
                <div className="flex items-center gap-4">
                  <div className="rounded-full bg-primary text-primary-foreground w-12 h-12 flex items-center justify-center">
                    SM
                  </div>
                  <div>
                    <h4 className="font-bold">Sarah Martinez</h4>
                    <p className="text-sm text-muted-foreground">Loyal Customer</p>
                  </div>
                </div>
                <p className="mt-4 text-muted-foreground">
                  &ldquo;I&apos;ve been coming to Pinoy Eats for years and it&apos;s always my
                  go-to spot for authentic Filipino cuisine. The staff is so
                  friendly and the food is consistently delicious.&rdquo;
                </p>
              </Card>
              <Card className="bg-background p-6 rounded-xl shadow-sm">
                <div className="flex items-center gap-4">
                  <div className="rounded-full bg-primary text-primary-foreground w-12 h-12 flex items-center justify-center">
                    RG
                  </div>
                  <div>
                    <h4 className="font-bold">Robert Garcia</h4>
                    <p className="text-sm text-muted-foreground">Foodie Enthusiast</p>
                  </div>
                </div>
                <p className="mt-4 text-muted-foreground">
                  &ldquo;Pinoy Eats is a hidden gem! The halo-halo is the best I&apos;ve
                  ever had, and the other dishes are equally impressive. If
                  you&apos;re looking for a taste of the Philippines, this is the
                  place to go.&rdquo;
                </p>
              </Card>
            </div>
          </div>
        </section>
        <section id="contact" className="w-full py-12 sm:py-24 md:py-32 flex items-center justify-center">
          <div className="container px-4 md:px-6 max-w-5xl mx-auto">
            <div className="grid gap-8 sm:grid-cols-2 lg:grid-cols-3">
              <div className="space-y-4">
                <h2 className="text-3xl font-bold tracking-tighter sm:text-4xl md:text-5xl">Visit Us</h2>
                <div className="space-y-2">
                  <p className="text-muted-foreground">
                    <ClockIcon className="mr-2 inline-block h-4 w-4" />
                    Open Daily: 11am - 8pm
                  </p>
                  <p className="text-muted-foreground">
                    <MapPinIcon className="mr-2 inline-block h-4 w-4" />
                    123 Tims sports complex food truck, San Antonio, TX
                  </p>
                  <p className="text-muted-foreground">
                    <PhoneIcon className="mr-2 inline-block h-4 w-4" />
                    (123) 456-7890
                  </p>
                </div>
              </div>
              <div className="col-span-2 space-y-4">
                <h2 className="text-3xl font-bold tracking-tighter sm:text-4xl md:text-5xl">Get in Touch</h2>
                <form className="grid gap-4">
                  <div className="grid grid-cols-2 gap-4">
                    <Input type="text" placeholder="Name" className="w-full" />
                    <Input type="email" placeholder="Email" className="w-full" />
                  </div>
                  <Input type="text" placeholder="Subject" className="w-full" />
                  <Textarea placeholder="Message" className="w-full" rows={4} />
                  <Button type="submit" className="justify-self-end">
                    Submit
                  </Button>
                </form>
              </div>
            </div>
          </div>
        </section>
      </main>
      <footer className="flex flex-col gap-2 sm:flex-row py-6 w-full shrink-0 items-center px-4 md:px-6 border-t">
        <p className="text-xs text-muted-foreground">&copy; 2024 Pinoy Eats. All rights reserved.</p>
        <nav className="sm:ml-auto flex gap-4 sm:gap-6">
          <Link href="#" className="text-xs hover:underline underline-offset-4" prefetch={false}>
            Privacy Policy
          </Link>
          <Link href="#" className="text-xs hover:underline underline-offset-4" prefetch={false}>
            Terms of Service
          </Link>
        </nav>
      </footer>
    </div>
  )
}

function ClockIcon(props: React.SVGProps<SVGSVGElement>) {
  return (
    <svg
      {...props}
      xmlns="http://www.w3.org/2000/svg"
      width="24"
      height="24"
      viewBox="0 0 24 24"
      fill="none"
      stroke="currentColor"
      strokeWidth="2"
      strokeLinecap="round"
      strokeLinejoin="round"
    >
      <circle cx="12" cy="12" r="10" />
      <polyline points="12 6 12 12 16 14" />
    </svg>
  )
}


function MapPinIcon(props: React.SVGProps<SVGSVGElement>) {
  return (
    <svg
      {...props}
      xmlns="http://www.w3.org/2000/svg"
      width="24"
      height="24"
      viewBox="0 0 24 24"
      fill="none"
      stroke="currentColor"
      strokeWidth="2"
      strokeLinecap="round"
      strokeLinejoin="round"
    >
      <path d="M20 10c0 6-8 12-8 12s-8-6-8-12a8 8 0 0 1 16 0Z" />
      <circle cx="12" cy="10" r="3" />
    </svg>
  )
}


function PhoneIcon(props: React.SVGProps<SVGSVGElement>) {
  return (
    <svg
      {...props}
      xmlns="http://www.w3.org/2000/svg"
      width="24"
      height="24"
      viewBox="0 0 24 24"
      fill="none"
      stroke="currentColor"
      strokeWidth="2"
      strokeLinecap="round"
      strokeLinejoin="round"
    >
      <path d="M22 16.92v3a2 2 0 0 1-2.18 2 19.79 19.79 0 0 1-8.63-3.07 19.5 19.5 0 0 1-6-6 19.79 19.79 0 0 1-3.07-8.67A2 2 0 0 1 4.11 2h3a2 2 0 0 1 2 1.72 12.84 12.84 0 0 0 .7 2.81 2 2 0 0 1-.45 2.11L8.09 9.91a16 16 0 0 0 6 6l1.27-1.27a2 2 0 0 1 2.11-.45 12.84 12.84 0 0 0 2.81.7A2 2 0 0 1 22 16.92z" />
    </svg>
  )
}


function TruckIcon(props: React.SVGProps<SVGSVGElement>) {
  return (
    <svg
      {...props}
      xmlns="http://www.w3.org/2000/svg"
      width="24"
      height="24"
      viewBox="0 0 24 24"
      fill="none"
      stroke="currentColor"
      strokeWidth="2"
      strokeLinecap="round"
      strokeLinejoin="round"
    >
      <path d="M14 18V6a2 2 0 0 0-2-2H4a2 2 0 0 0-2 2v11a1 1 0 0 0 1 1h2" />
      <path d="M15 18H9" />
      <path d="M19 18h2a1 1 0 0 0 1-1v-3.65a1 1 0 0 0-.22-.624l-3.48-4.35A1 1 0 0 0 17.52 8H14" />
      <circle cx="17" cy="18" r="2" />
      <circle cx="7" cy="18" r="2" />
    </svg>
  )
}
